"Make the tarnish attack indiscriminately?" = false
#Combine with the first option to cause a war of incredible magnitude. (This may cause lag) 
"Make entities target the tarnish above all else?" = false

